"""my_migrashion

Revision ID: 6bf850e21322
Revises: 
Create Date: 2022-12-21 19:20:28.759252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf850e21322'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('bday', sa.Date(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lang',
    sa.Column('name', sa.String(length=2), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('author_language_join',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('lang_name', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['lang_name'], ['lang.name'], ),
    sa.PrimaryKeyConstraint('author_id', 'lang_name')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('year_publication', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('READ', 'PLANNED', name='bookstatus'), nullable=True),
    sa.Column('lang_name', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['lang_name'], ['lang.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_author_join',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'author_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_author_join')
    op.drop_table('book')
    op.drop_table('author_language_join')
    op.drop_table('lang')
    op.drop_table('author')
    # ### end Alembic commands ###
